name: infrastructure - deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 60  
    defaults:
      run:
        working-directory: infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.20.2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.51.3
      - name: Install terratest log parser
        run: ./install_linux_terratest_log_parser.sh          
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.44.1
      - run: make tf-lint
      - name: deploy environment
        env:
          TF_IN_AUTOMATION: 1
          ENVIRONMENT: paul-website
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_CLIENT_CERT_DATA: ${{ secrets.KUBE_CLIENT_CERT_PEM }}
          KUBE_CLIENT_KEY_DATA: ${{ secrets.KUBE_CLIENT_KEY_PEM }}
          KUBE_CLUSTER_CA_CERT_DATA: ${{secrets.KUBE_CLUSTER_CA_CERT_PEM }}          
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make tf-apply-all-auto-approve env=paul-website module=website