name: website - build and push

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "website/**"
      - .github/workflows/website-build.yml

jobs:
  test:
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run audit:security
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: website/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
